apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: strimzi
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/strimzi/strimzi-kafka-operator'
    path: 'helm-charts/helm3/strimzi-kafka-operator'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
