apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: diego.pessoa
  namespace: ingestion
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: users-json
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operations:
          - Read
        host: "*"
      # Example Producer Acls for topic my-topic
      - resource:
          type: topic
          name: users-json
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"